### ISSUE TITLE
Find alternative to CSV to array

### ISSUE THREAD

**Issue by hadley** [r-lib/diffviewer#7]
http://www.speqmath.com/tutorials/csv2array/ doesn't have any licensing information so we can't use it.

@jbkunst can you please find an alternative?

**Comment by jbkunst** [comment]
@hadley 

I made a quick research. I found and implemented PapaParse (https://github.com/mholt/PapaParse), looks a good alternative:

- MIT License
- Active development (last commit 9 days ago)
- Robust in terms of options and error handling 
- 9k starts on gh

**Comment by jbkunst** [comment]
Thank you. I will take the considerations from here forward. I will make the changes via PR
